package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWeixinUser<M extends BaseWeixinUser<M>> extends Model<M> implements IBean {

	public void setOPENID(java.lang.String OPENID) {
		set("OPENID", OPENID);
	}

	public java.lang.String getOPENID() {
		return get("OPENID");
	}

	public void setNICKNAME(java.lang.String NICKNAME) {
		set("NICKNAME", NICKNAME);
	}

	public java.lang.String getNICKNAME() {
		return get("NICKNAME");
	}

	public void setUSERNAME(java.lang.String USERNAME) {
		set("USERNAME", USERNAME);
	}

	public java.lang.String getUSERNAME() {
		return get("USERNAME");
	}

	public void setPHONENO(java.lang.String PHONENO) {
		set("PHONENO", PHONENO);
	}

	public java.lang.String getPHONENO() {
		return get("PHONENO");
	}

	public void setADDRESSED(java.lang.String ADDRESSED) {
		set("ADDRESSED", ADDRESSED);
	}

	public java.lang.String getADDRESSED() {
		return get("ADDRESSED");
	}

	public void setLINKNAME(java.lang.String LINKNAME) {
		set("LINKNAME", LINKNAME);
	}

	public java.lang.String getLINKNAME() {
		return get("LINKNAME");
	}

	public void setLINKTELNO(java.lang.String lINKTELNO) {
		set("lINKTELNO", lINKTELNO);
	}

	public java.lang.String getLINKTELNO() {
		return get("lINKTELNO");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

}
