package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistributionPlan<M extends BaseDistributionPlan<M>> extends Model<M> implements IBean {

	public void setPLANID(java.lang.Long PLANID) {
		set("PLANID", PLANID);
	}

	public java.lang.Long getPLANID() {
		return get("PLANID");
	}

	public void setORDERID(java.lang.Long ORDERID) {
		set("ORDERID", ORDERID);
	}

	public java.lang.Long getORDERID() {
		return get("ORDERID");
	}

	public void setPRODUCTID(java.lang.Long PRODUCTID) {
		set("PRODUCTID", PRODUCTID);
	}

	public java.lang.Long getPRODUCTID() {
		return get("PRODUCTID");
	}

	public void setPLANDATE(java.lang.String PLANDATE) {
		set("PLANDATE", PLANDATE);
	}

	public java.lang.String getPLANDATE() {
		return get("PLANDATE");
	}

	public void setPLANSTATE(java.lang.String PLANSTATE) {
		set("PLANSTATE", PLANSTATE);
	}

	public java.lang.String getPLANSTATE() {
		return get("PLANSTATE");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

}
