package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenuTree<M extends BaseMenuTree<M>> extends Model<M> implements IBean {

	public void setMENUID(java.lang.Long MENUID) {
		set("MENUID", MENUID);
	}

	public java.lang.Long getMENUID() {
		return get("MENUID");
	}

	public void setMENUNAME(java.lang.String MENUNAME) {
		set("MENUNAME", MENUNAME);
	}

	public java.lang.String getMENUNAME() {
		return get("MENUNAME");
	}

	public void setMENUCODE(java.lang.String MENUCODE) {
		set("MENUCODE", MENUCODE);
	}

	public java.lang.String getMENUCODE() {
		return get("MENUCODE");
	}

	public void setTREENO(java.lang.String TREENO) {
		set("TREENO", TREENO);
	}

	public java.lang.String getTREENO() {
		return get("TREENO");
	}

	public void setPMID(java.lang.Integer PMID) {
		set("PMID", PMID);
	}

	public java.lang.Integer getPMID() {
		return get("PMID");
	}

	public void setISHIDDEN(java.lang.String ISHIDDEN) {
		set("ISHIDDEN", ISHIDDEN);
	}

	public java.lang.String getISHIDDEN() {
		return get("ISHIDDEN");
	}

	public void setISLEAF(java.lang.String ISLEAF) {
		set("ISLEAF", ISLEAF);
	}

	public java.lang.String getISLEAF() {
		return get("ISLEAF");
	}

	public void setSORTNO(java.lang.Integer SORTNO) {
		set("SORTNO", SORTNO);
	}

	public java.lang.Integer getSORTNO() {
		return get("SORTNO");
	}

}
