package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlanItem<M extends BasePlanItem<M>> extends Model<M> implements IBean {

	public void setITEMID(java.lang.Long ITEMID) {
		set("ITEMID", ITEMID);
	}

	public java.lang.Long getITEMID() {
		return get("ITEMID");
	}

	public void setPLANID(java.lang.Long PLANID) {
		set("PLANID", PLANID);
	}

	public java.lang.Long getPLANID() {
		return get("PLANID");
	}

	public void setCID(java.lang.Long CID) {
		set("CID", CID);
	}

	public java.lang.Long getCID() {
		return get("CID");
	}

	public void setITEMNUMBER(java.lang.Long ITEMNUMBER) {
		set("ITEMNUMBER", ITEMNUMBER);
	}

	public java.lang.Long getITEMNUMBER() {
		return get("ITEMNUMBER");
	}

}
