package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmessage<M extends BaseTmessage<M>> extends Model<M> implements IBean {

	public void setMSGID(java.lang.Long MSGID) {
		set("MSGID", MSGID);
	}

	public java.lang.Long getMSGID() {
		return get("MSGID");
	}

	public void setOPENID(java.lang.Long OPENID) {
		set("OPENID", OPENID);
	}

	public java.lang.Long getOPENID() {
		return get("OPENID");
	}

	public void setMSGTITLE(java.lang.String MSGTITLE) {
		set("MSGTITLE", MSGTITLE);
	}

	public java.lang.String getMSGTITLE() {
		return get("MSGTITLE");
	}

	public void setMSG(java.lang.String MSG) {
		set("MSG", MSG);
	}

	public java.lang.String getMSG() {
		return get("MSG");
	}

	public void setCREATEDATE(java.util.Date CREATEDATE) {
		set("CREATEDATE", CREATEDATE);
	}

	public java.util.Date getCREATEDATE() {
		return get("CREATEDATE");
	}

}
