package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}

	public java.lang.Long getUserid() {
		return get("userid");
	}

	public void setUno(java.lang.String uno) {
		set("uno", uno);
	}

	public java.lang.String getUno() {
		return get("uno");
	}

	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}

	public java.lang.String getUname() {
		return get("uname");
	}

	public void setUtype(java.lang.Integer utype) {
		set("utype", utype);
	}

	public java.lang.Integer getUtype() {
		return get("utype");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

}
