package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setPRODUCTID(java.lang.Long PRODUCTID) {
		set("PRODUCTID", PRODUCTID);
	}

	public java.lang.Long getPRODUCTID() {
		return get("PRODUCTID");
	}

	public void setPRODUCTNAME(java.lang.String PRODUCTNAME) {
		set("PRODUCTNAME", PRODUCTNAME);
	}

	public java.lang.String getPRODUCTNAME() {
		return get("PRODUCTNAME");
	}

	public void setCYCLE(java.lang.String CYCLE) {
		set("CYCLE", CYCLE);
	}

	public java.lang.String getCYCLE() {
		return get("CYCLE");
	}

	public void setPRICE(java.lang.Double PRICE) {
		set("PRICE", PRICE);
	}

	public java.lang.Double getPRICE() {
		return get("PRICE");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

}
