package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommodities<M extends BaseCommodities<M>> extends Model<M> implements IBean {

	public void setCID(java.lang.Long CID) {
		set("CID", CID);
	}

	public java.lang.Long getCID() {
		return get("CID");
	}

	public void setCNAME(java.lang.String CNAME) {
		set("CNAME", CNAME);
	}

	public java.lang.String getCNAME() {
		return get("CNAME");
	}

}
