package com.loong.jfinalwebdemo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setORDERID(java.lang.Long ORDERID) {
		set("ORDERID", ORDERID);
	}

	public java.lang.Long getORDERID() {
		return get("ORDERID");
	}

	public void setOPENID(java.lang.String OPENID) {
		set("OPENID", OPENID);
	}

	public java.lang.String getOPENID() {
		return get("OPENID");
	}

	public void setPRODUCTID(java.lang.Long PRODUCTID) {
		set("PRODUCTID", PRODUCTID);
	}

	public java.lang.Long getPRODUCTID() {
		return get("PRODUCTID");
	}

	public void setPRICE(java.lang.Double PRICE) {
		set("PRICE", PRICE);
	}

	public java.lang.Double getPRICE() {
		return get("PRICE");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}

	public java.lang.String getREMARK() {
		return get("REMARK");
	}

}
