package com.loong.jfinalwebdemo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("commodities", "CID", Commodities.class);
		arp.addMapping("distribution_plan", "PLANID", DistributionPlan.class);
		arp.addMapping("menu_tree", "MENUID", MenuTree.class);
		arp.addMapping("orders", "ORDERID", Orders.class);
		arp.addMapping("plan_item", "ITEMID", PlanItem.class);
		arp.addMapping("product", "PRODUCTID", Product.class);
		arp.addMapping("product_item", "ITEMID", ProductItem.class);
		arp.addMapping("sys_user", "USERID", SysUser.class);
		arp.addMapping("tmessage", "MSGID", Tmessage.class);
		arp.addMapping("weixin_user", "OPENID", WeixinUser.class);
	}
}

