package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseCommodities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commodities extends BaseCommodities<Commodities> {
	public static final Commodities dao = new Commodities();
}
