package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseMenuTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuTree extends BaseMenuTree<MenuTree> {
	public static final MenuTree dao = new MenuTree();
}
