package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {
	public static final Orders dao = new Orders();
}
