package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseProductItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductItem extends BaseProductItem<ProductItem> {
	public static final ProductItem dao = new ProductItem();
}
