package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUser extends BaseSysUser<SysUser> {
	public static final SysUser dao = new SysUser();

	/**
	 * 根据用户名获取对象
	 */
	public SysUser login(SysUser sysUser) {
		String sql = "select userid,uname from sys_user where uno=? and pwd=?";
		return super.findFirst(sql, sysUser.getUno(), sysUser.getPwd());
	}

}
