package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseTmessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tmessage extends BaseTmessage<Tmessage> {
	public static final Tmessage dao = new Tmessage();
}
