package com.loong.jfinalwebdemo.model;

import com.loong.jfinalwebdemo.model.base.BaseWeixinUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeixinUser extends BaseWeixinUser<WeixinUser> {
	public static final WeixinUser dao = new WeixinUser();
}
