package com.nstc.sanmuyuan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTmessage<M extends BaseTmessage<M>> extends Model<M> implements IBean {

	public void setMsgid(java.lang.Long msgid) {
		set("msgid", msgid);
	}

	public java.lang.Long getMsgid() {
		return get("msgid");
	}

	public void setOpenid(java.lang.Long openid) {
		set("openid", openid);
	}

	public java.lang.Long getOpenid() {
		return get("openid");
	}

	public void setMsgtitle(java.lang.String msgtitle) {
		set("msgtitle", msgtitle);
	}

	public java.lang.String getMsgtitle() {
		return get("msgtitle");
	}

	public void setMsg(java.lang.String msg) {
		set("msg", msg);
	}

	public java.lang.String getMsg() {
		return get("msg");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

}
