package com.nstc.sanmuyuan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommodities<M extends BaseCommodities<M>> extends Model<M> implements IBean {

	public void setCid(java.lang.Long cid) {
		set("cid", cid);
	}

	public java.lang.Long getCid() {
		return get("cid");
	}

	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}

	public java.lang.String getCname() {
		return get("cname");
	}

}
