package com.nstc.sanmuyuan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenuTree<M extends BaseMenuTree<M>> extends Model<M> implements IBean {

	public void setMenuid(java.lang.Long menuid) {
		set("menuid", menuid);
	}

	public java.lang.Long getMenuid() {
		return get("menuid");
	}

	public void setMenuname(java.lang.String menuname) {
		set("menuname", menuname);
	}

	public java.lang.String getMenuname() {
		return get("menuname");
	}

	public void setMenucode(java.lang.String menucode) {
		set("menucode", menucode);
	}

	public java.lang.String getMenucode() {
		return get("menucode");
	}

	public void setTreeno(java.lang.String treeno) {
		set("treeno", treeno);
	}

	public java.lang.String getTreeno() {
		return get("treeno");
	}

	public void setPmid(java.lang.Integer pmid) {
		set("pmid", pmid);
	}

	public java.lang.Integer getPmid() {
		return get("pmid");
	}

	public void setIshidden(java.lang.String ishidden) {
		set("ishidden", ishidden);
	}

	public java.lang.String getIshidden() {
		return get("ishidden");
	}

	public void setIsleaf(java.lang.String isleaf) {
		set("isleaf", isleaf);
	}

	public java.lang.String getIsleaf() {
		return get("isleaf");
	}

	public void setSortno(java.lang.Integer sortno) {
		set("sortno", sortno);
	}

	public java.lang.Integer getSortno() {
		return get("sortno");
	}

}
