package com.nstc.sanmuyuan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setProductid(java.lang.Long productid) {
		set("productid", productid);
	}

	public java.lang.Long getProductid() {
		return get("productid");
	}

	public void setProductname(java.lang.String productname) {
		set("productname", productname);
	}

	public java.lang.String getProductname() {
		return get("productname");
	}

	public void setCycle(java.lang.String cycle) {
		set("cycle", cycle);
	}

	public java.lang.String getCycle() {
		return get("cycle");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setDetails(java.lang.String details) {
		set("details", details);
	}

	public java.lang.String getDetails() {
		return get("details");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
