package com.nstc.sanmuyuan.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistributionPlan<M extends BaseDistributionPlan<M>> extends Model<M> implements IBean {

	public void setPlanid(java.lang.Long planid) {
		set("planid", planid);
	}

	public java.lang.Long getPlanid() {
		return get("planid");
	}

	public void setOrderid(java.lang.Long orderid) {
		set("orderid", orderid);
	}

	public java.lang.Long getOrderid() {
		return get("orderid");
	}

	public void setProductid(java.lang.Long productid) {
		set("productid", productid);
	}

	public java.lang.Long getProductid() {
		return get("productid");
	}

	public void setPlandate(java.lang.String plandate) {
		set("plandate", plandate);
	}

	public java.lang.String getPlandate() {
		return get("plandate");
	}

	public void setPlanstate(java.lang.String planstate) {
		set("planstate", planstate);
	}

	public java.lang.String getPlanstate() {
		return get("planstate");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
