package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseCommodities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commodities extends BaseCommodities<Commodities> {
	public static final Commodities dao = new Commodities();
}
