package com.nstc.sanmuyuan.model;

import java.util.List;

import com.nstc.sanmuyuan.model.base.BaseCommodities;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Commodities extends BaseCommodities<Commodities> {
	public static final Commodities dao = new Commodities();

	public List<Commodities> list() {
		return find("select cid,cname from COMMODITIES");
	}
}
