package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseDistributionPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributionPlan extends BaseDistributionPlan<DistributionPlan> {
	public static final DistributionPlan dao = new DistributionPlan();
}
