package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseMenuTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MenuTree extends BaseMenuTree<MenuTree> {
	public static final MenuTree dao = new MenuTree();
}
