package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseOrders;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {
	public static final Orders dao = new Orders();
}
