package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BasePlanItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlanItem extends BasePlanItem<PlanItem> {
	public static final PlanItem dao = new PlanItem();
}
