package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseProductItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductItem extends BaseProductItem<ProductItem> {
	public static final ProductItem dao = new ProductItem();
}
