package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseProductItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductItem extends BaseProductItem<ProductItem> {
	public static final ProductItem dao = new ProductItem();

	public void setCname(java.lang.String cname) {
		set("cname", cname);
	}

	public java.lang.String getCname() {
		return get("cname");
	}
}
