package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseTmessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tmessage extends BaseTmessage<Tmessage> {
	public static final Tmessage dao = new Tmessage();
}
