package com.nstc.sanmuyuan.model;

import com.nstc.sanmuyuan.model.base.BaseWeixinUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeixinUser extends BaseWeixinUser<WeixinUser> {
	public static final WeixinUser dao = new WeixinUser();
}
