package com.nstc.sanmuyuan.model;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.jfinal.plugin.activerecord.ActiveRecordException;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;
import com.jfinal.plugin.activerecord.Page;
import com.nstc.sanmuyuan.model.base.BaseWeixinUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeixinUser extends BaseWeixinUser<WeixinUser> {
	public static final WeixinUser dao = new WeixinUser();

	public List<WeixinUser> list() {
		return find("select id,openid,nickname, ifnull(phoneno,'')phoneno,ifnull(addressed,'')addressed,ifnull(linkname,'')linkname,ifnull(linktelno,'')linktelno,ifnull(remark,'')remark from WEIXIN_USER order by id");
	}

	public boolean batchSave(List<WeixinUser> userInfos) throws Exception {

		try {
			return Db.tx(new IAtom() {

				@Override
				public boolean run() throws SQLException {
					boolean reslut = false;
					for (WeixinUser weixinUser : userInfos) {
						try {
							weixinUser.save();
							reslut = true;
						} catch (Exception e) {
							if (e.getMessage().contains("MySQLIntegrityConstraintViolationException") && e.getMessage().contains("PRIMARY")) {
								// 依靠数据库去重复（主键openid），后期再优化处理
								reslut = true;
							} else {
								throw new SQLException(e);
							}
						}
					}
					return reslut;
				}
			});
		} catch (ActiveRecordException e) {
			throw new Exception(e);
		}
	}

	public Page<WeixinUser> paginate(Map<String, String> params, int pageNumber, int pageSize) {

		String strSelect = "select id,openid,nickname, ifnull(remark,'')remark, ifnull(phoneno,'')phoneno,ifnull(addressed,'')addressed";

		String sqlExceptSelect = "from WEIXIN_USER ";
		sqlExceptSelect += " where 1=1 ";
		if (params != null && params.size() > 0) {
			if (params.get("weixinuserid") != null && !params.get("weixinuserid").equals("")) {
				sqlExceptSelect += " and id like '%" + params.get("weixinuserid") + "%'";
			}
			if (params.get("nickname") != null && !params.get("nickname").equals("")) {
				sqlExceptSelect += " and nickname like '%" + params.get("nickname") + "%'";
			}
			if (params.get("remark") != null && !params.get("remark").equals("")) {
				sqlExceptSelect += " and remark like '%" + params.get("remark") + "%'";
			}

		}
		sqlExceptSelect += "order by id asc";

		return paginate(pageNumber, pageSize, strSelect, sqlExceptSelect);
	}
}
